name: Dev CI/CD - .NET Build, Migrate, Deploy

on:
  pull_request:
    branches:
      - master            # CI only (build + test)
  push:
    branches:
      - master            # Full CI/CD after merge
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

# Prevent multiple deployments at the same time
concurrency:
  group: dev-environment
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION: '**/Analytics.Reporting.Portal.Web.sln'
  HOST_PROJECT: '**/Analytics.Reporting.Portal.Web.Host.csproj'
  EF_PROJECT_DIR: 'src/Analytics.Reporting.Portal.EntityFrameworkCore'
  EF_PROJECT_FILE: 'Analytics.Reporting.Portal.EntityFrameworkCore.csproj'
  BUILD_CONFIG: 'Release'
  PUBLISH_OUTPUT: './publish'
  ZIP_NAME: 'release.zip'
  AZURE_WEBAPP_NAME: 'app-aiz-gda-ea-portal-api-dev-cus'
  AZURE_SLOT_NAME: 'development'

jobs:
  # -----------------------------
  # CI : Build + Test
  # -----------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}


  # -----------------------------
  # CD : Deploy to Azure (DEV)
  # -----------------------------
  deploy:
    if: github.event_name == 'push'      # Deploy ONLY after merge
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Check Azure secrets presence
        run: |
          echo "CLIENT_ID set: ${{ secrets.TEST_ENV != '' }}"
          echo "TENANT_ID set: ${{ secrets.TEST_ENV_1 != '' }}"
          echo "SUBSCRIPTION_ID set: ${{ vars.AZURE_SUBSCRIPTION_ID != '' }}"
          echo "CLIENT_SECRET set: ${{ secrets.AZURE_CLIENT_SECRET != '' }}"
 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: aspnet-publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: >
            {"clientId":"${{ vars.AZURE_CLIENT_ID }}",
             "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
             "subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}",
             "tenantId":"${{ vars.AZURE_TENANT_ID }}"}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_SLOT_NAME }}
          package: ./${{ env.ZIP_NAME }}

      - name: Deployment confirmation
        run: echo "Deployed successfully to DEV environment"
